console.log(14);
console.log(5%2);
console.log(5%4);
console.log('I\'M MARY POPPINS, Y\'ALL!');
console.log("Wanda" + "Vision");
console.log("Matt".length + "Riley".length);
console.log("Avengers: Endgame"[16]);
console.log("\\");
console.log(5 ** 4 - 9);
console.log("I".length % "Am".length - "Iron".length % "Man".length);
console.log("I".length - "Am".length + "Iron".length - "Man".length);
console.log("I".length + "Am".length + ("Iron".length % 2) - "Man".length);
console.log("CAP"[1]);
console.log("VISION"[0]);
console.log("HAWKEYE"[4]);
console.log("NICK FURY"[0]);
console.log("GROOT"[0]);
console.log("DOCTOR STRANGE"[13]);
console.log("THOR"[3]);
console.log("STAR-LORD"[0]);
var m = 10;
var c = 5;
var u = m + c;
console.log(u);